name: Deploy Multi-Repo to GitHub Pages

on:
  push:
    branches: [ main,test ]
  workflow_dispatch: # 手动触发

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone private repo (optional)
        uses: actions/checkout@v4
        with:
          repository: LY1806620741/17fei
          path: ./17fei
          fetch-depth: 0
          token: ${{ secrets.SLEF_DEPLOY }} # 私有仓库需用 PAT
      
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      
      # https://lume.land/docs/advanced/deployment/#github-pages
      - name: Merge code from other repos
        run: |
          cd 17fei
          deno task build
          cd ..
          mkdir dist
          ls
          cp -r ./17fei/_fresh/ ./dist/17fei/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4